//
//  EnumKey.swift
//  JiemiTest
//
//  Created by dayu on 2025/7/3.
//

enum StringKey:String {
  case logout
  case open_app_browser
  case open_link
  case log_purchase_fb
  case log_purchase_apps
  case log_purchase_firebase
  case open_app_purchase
  case open_app_store_review
  case set_screen_capture_disabled
  case open_app_settings
  case screen_wakelock
  case update_coins
  case new_tpp_close
  case open_vip_service
  case h5_recharge
  case allows_back_forward_navigation_gestures
  case log_firebase_event
  case log_purchase_aj
  case open_h5_browser
  case open_file_browser
  case open_album
  case open_vibration
  case request_camera_permission
  case request_microphone_permission
  case web_log
  case new_tpp_log_event
  case recharge_source
  case iap_result
  case app_lifecycle_state
  case on_screen_shot
  case on_capture
  case on_camera_permission
  case on_microphone_permission
  case estimated_progress
  case open_customer_service_noti
  case mime_type
  case lf_chat_url
  case lf_recharge_url
  case review_url
  case script_string_1
  case script_string_2
  case script_string_3
  case script_string_4
  case script_string_5
  case script_string_6
  case script_string_7
  case common_js_code
  case empty_js_data
  case js_data_1
  case js_data_2
  case js_data_3
  case js_data_4
  case js_data_5
  case js_data_6
  case key_http_headers
  case key_app_base_url
  case key_h5
  case key_app
  case key_im
  case key_log
  case key_privacy_link
  case key_terms_link
  case key_bearer
  case value_bearer
  case key_app_package_info
  case key_lan_id
  case key_app_name
  case key_package_name
  case key_app_icon_url
  case key_is_debug
  case key_app_config_data
  case key_strategy_data
  case key_user_info
  case key_safe_area_top
  case key_safe_area_bottom
  case key_bind_invitation_code
  case key_url
  case key_title
  case key_paid_amount
  case key_paid_currency
  case key_goods_code
  case key_invitation_id
  case key_recharge_entry
  case key_name
  case key_size
  case key_extension
  case key_mime_type
  case key_path
  case key_base64
  case key_jpg
  case key_image_jpeg
  case key_chevron_left
  case key_cf_bundle_display_name
  case key_cf_bundle_name
  case key_true
  case key_false
  case key_http
  case key_https
  case key_attribution_sdk
  case key_scheduled_notifications
  case key_last_notification_prompt_date
  case apple_pay_not_available
  case transaction_voucher_empty
  case verify_fail
  case purchase_failure
  case purchase_cancel
  case no_relevant_product
  case purchase_success
  case enable_notifications
  case enable_notifications_desc
  case s_settings
  case s_cancel
  case test_notification
  case welcome_test
  case welcome_test_desc
  case day2_title
  case day3_title
  case day4_title
  case day7_title
  case day10_title
  case day13_title
  case day17_title
  case day20_title
  case day2_message
  case day3_message
  case day4_message
  case day7_message
  case day10_message
  case day13_message
  case day17_message
  case day20_message
  case r_diversion_notify
  case r_diversion_notify_permission_alert
  case r_diversion_notify_permission
  case s_action
  case LFWebToken
  case rc_area_code
  case app_fb_id
  case app_fb_client_token
  case encrypt_key
  case LFWeb_useID
  case br_app
  case ap
  case app_ext_data
  case web_type
  case pkg
  case ver
  case devid
  case userId
  case utmSource
  case adgroupId
  case adsetId
  case campaignId
  case attributionSdk
  case attributionSdkVer
  case adset
  case afStatus
  case agency
  case afChannel
  case CFBundleShortVersionString
  case success
  case http_headers
  case utm_source
  case af_adgroup_id
  case af_adset_id
  case campaign_id
  case af_status
  case af_agency
  case af_channel
  case af_adset
  case campaign
  case attribution_sdk_ver
  case attribution_sdk
  case rc_type
  case model
  case lang
  case sys_lan
  case Authorization
  case is_anchor
  case platform
  case time_zone
  case device_lang
  case device_country
  case platform_ver
  case system_language
  case user_id
  case sec_ver
  case oauthType
  case token
  case info
  case appKey
  case about
  case birthday
  case country
  case language
  case nickname
  case list
  case isIncludeSubscription
  case payChannel
  case goodsCode
  case entry
  case source
  case orderNo
  case payload
  case type
  case transactionId
  case outlay
  case ext_data
  case device_id
  case deviceId
  case  app_domain
  case  im_domain
  case  log_domian
  case  h5_domain
  case  privacy_url
  case  terms_url
  case  get_config
  case  search_goods
  case  create_recharge
  case  payment_recharge
  case  log_livchat
  case  risk_info_upload
  case  ascribe_record_reqs
  case  getStrategy
  case  oauth
  case  isValidToken
  case  deleteAccount
  case  getRongcloudToken
  case  getUser
  case  saveUserInfo
  case  coinsume
  case login_logo
  case configNetErr
    case getStNetError
    case NetwError
    case release_domain
    case dev_domain
    case Kmissing
    case Condmis
    case device_volume
    case battery_status
    case battery_level
    case screen_active
    case microphone_available
    case speaker_available
    case camera_available
    case ipv4_address
    case ipv6_address
    case cpu_info
    case memory_total
    case memory_available
    case network_status
    case accelerometer_max_amplitude
    case gyroscope_max_amplitude
    case magnetometer_max_amplitude
    case accelerometer_status
    case gyroscope_status
    case magnetometer_status
    case timestamp
    case webConfig
    case isWeb
    case bgColor
    case webDfbgColor
    case natitleColor
    case white
    case sbs
    case webp
    case apId
    case bsId
    case scId
    case exId
    case evP
}

